describe('test suite lista de desejo', () => {
    it('Adicionar livro', () => {
        cy.visit('/');
        cy.get('.nav-link > .logosomb').click()
        cy.get('.btn-primary').click()
        cy.get('#id_username').type('Joaquim')
        cy.get('#id_password').type('testando')
        cy.get('.btn').click()
        cy.get(':nth-child(4) > a > .bx').click()
        cy.get('.btn').click()
        cy.get('#titulo').type('Pequeno principe')
        cy.get('#autor').type('Antoine de Saint-Exupéry')
        cy.get('#anopublicado').type('1943')
        cy.get('.btn').click()
        cy.get('.list-group > :nth-child(1)').invoke('text').should('have.string', 'Pequeno principe - Antoine de Saint-Exupéry (1943)')
    })
    it('Adicionar outro livro', () => {
        cy.visit('/');
        cy.get('.nav-link > .logosomb').click()
        cy.get('.btn-primary').click()
        cy.get('#id_username').type('Joaquim')
        cy.get('#id_password').type('testando')
        cy.get('.btn').click()
        cy.get(':nth-child(4) > a > .bx').click()
        cy.get('.btn-success').click()
        cy.get('#titulo').type('Romeu e Julieta')
        cy.get('#autor').type('William Shakespear')
        cy.get('#anopublicado').type('1595')
        cy.get('.btn').click()
        cy.get('.list-group > :nth-child(2)').invoke('text').should('have.string', 'Romeu e Julieta - William Shakespear (1595)')
    })
    it('Mover livro para biblioteca', () => {
        cy.visit('/');
        cy.get('.nav-link > .logosomb').click()
        cy.get('.btn-primary').click()
        cy.get('#id_username').type('Joaquim')
        cy.get('#id_password').type('testando')
        cy.get('.btn').click()
        cy.get(':nth-child(4) > a > .bx').click()
        cy.get('[action="/mainapp/lista_desejos/add_para_colecao/47/"] > .btn').click()
        cy.get(':nth-child(3) > a > .bx').click()
        cy.get('.list-group-item').click()
        cy.get('.card-title').invoke('text').should('have.string', 'Pequeno principe')
    })
    it('Remover livro da lista de desejo', () => {
        cy.visit('/');
        cy.get('.nav-link > .logosomb').click()
        cy.get('.btn-primary').click()
        cy.get('#id_username').type('Joaquim')
        cy.get('#id_password').type('testando')
        cy.get('.btn').click()
        cy.get(':nth-child(4) > a > .bx').click()
        cy.get('[action="/mainapp/lista_desejos/deletar/48/"] > .btn').click()
    })
  })