describe('test suite lista de desejo', () => {
    it('Adicionar livro', () => {
        cy.visit('/');
        cy.get('.nav-link > .logosomb').click()
        cy.get('.btn-primary').click()
        cy.get('#id_username').type('Joaquim')
        cy.get('#id_password').type('testando')
        cy.get('.btn').click()
        cy.get(':nth-child(4) > a > .bx').click()
        cy.get('.btn').click()
        cy.get('#titulo').type('Pequeno principe')
        cy.get('#autor').type('Antoine de Saint-Exupéry')
        cy.get('#anopublicado').type('1943')
        cy.get('.btn').click()
        cy.get('.list-group > :nth-child(1)').invoke('text').should('have.string', 'Pequeno principe - Antoine de Saint-Exupéry (1943)')
    })
    it('Mover livro para biblioteca', () => {
        cy.visit('/');
        cy.get('.nav-link > .logosomb').click()
        cy.get('.btn-primary').click()
        cy.get('#id_username').type('Joaquim')
        cy.get('#id_password').type('testando')
        cy.get('.btn').click()
        cy.get(':nth-child(4) > a > .bx').click()
        cy.get('#colect').click()
        cy.get(':nth-child(3) > a > .bx').click()
        cy.get('.list-group-item').click()
        cy.get('.card-title').invoke('text').should('have.string', 'Pequeno principe')
        cy.get('.col-md-8 > .btn-danger').click()
        cy.get('.modal-footer > form > .btn').click()
    })
    it('Remover livro da lista de desejo', () => {
        cy.visit('/');
        cy.get('.nav-link > .logosomb').click()
        cy.get('.btn-primary').click()
        cy.get('#id_username').type('Joaquim')
        cy.get('#id_password').type('testando')
        cy.get('.btn').click()
        cy.get(':nth-child(4) > a > .bx').click()
        cy.get('.btn').click()
        cy.get('#titulo').type('Pequeno principe')
        cy.get('#autor').type('Antoine de Saint-Exupéry')
        cy.get('#anopublicado').type('1943')
        cy.get('.btn').click()
        cy.get('#delet').click()
        cy.get('.list-group > p').invoke('text').should('have.string', 'Nenhum livro na sua lista de desejos.')
    })
  })